---
# OPTIONAL TASKS (needed to run checks from the host machine)
# - name: Uncomment the GitLab IP whitelist line
#   replace:
#     path: /etc/gitlab/gitlab.rb
#     regexp: '^# (gitlab_rails\[''monitoring_whitelist''\] = \[.*)\]$'
#     replace: '\1, ''20.20.20.1'']'

# - name: Reconfigure GitLab
#   command: gitlab-ctl reconfigure

# - name: Restart unicorn
#   command: gitlab-ctl restart unicorn
#   retries: 2
# END OF OPTIONAL TASKS

- name: Check GitLab health
  uri:
    url: http://127.0.0.1/-/health
    return_content: yes
  # Register the output of the module in a variable
  register: gitlab_health

- name: Print GitLab health
  debug:
    msg: "{{ gitlab_health.content }}"

# Run the other kind of health checks below

- name: Check GitLab readiness
  uri:
    url: http://127.0.0.1/-/readiness?all=1
    status_code: [200, 503]
  # Register the output of the module in a variable
  register: gitlab_readiness

# Quick check of the variable to explore it
# - name: quick check
#   debug:
#     msg: "{{ gitlab_readiness }}"

- name: Print GitLab readiness
  debug:
    msg: "{{ item }}: {{ gitlab_readiness.json[item][0].status }}"
  loop:
    - master_check
    - redis_check
  when: gitlab_readiness.json[item][0].status == "failed"

